config:
  main-app:
    url: http://localhost:9000

spring:
  graphql:
    graphiql:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL

logging:
  level:
    com.example.apigateway.feign: DEBUG

security:
  jwt:
    token-expiration-time: 15
    token-secret: kPJlyJLpui
    header-name: Authorization
    header-prefix: Bearer






