config:
  main-app:
    url: http://localhost:9000

spring:
  graphql:
    graphiql:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL

logging:
  level:
    com.example.apigateway.feign: DEBUG






